# This file was autogenerated by uv via the following command:
#    uv pip compile requirements.in
exceptiongroup==1.2.2
    # via pytest
geographiclib==2.0
    # via geopy
geopy==2.4.1
    # via -r requirements.in
iniconfig==2.0.0
    # via pytest
numpy==2.0.1
    # via pandas
packaging==24.1
    # via pytest
pandas==2.2.2
    # via -r requirements.in
pluggy==1.5.0
    # via pytest
pytest==8.3.2
    # via -r requirements.in
python-dateutil==2.9.0.post0
    # via pandas
pytz==2024.1
    # via pandas
six==1.16.0
    # via python-dateutil
tomli==2.0.1
    # via pytest
tzdata==2024.1
    # via pandas
uv==0.2.33
    # via -r requirements.in
